Name:           ros-melodic-hls-lfcd-lds-driver
Version:        1.1.0
Release:        1%{?dist}
Summary:        ROS hls_lfcd_lds_driver package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/hls_lfcd_lds_driver
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-std-msgs
BuildRequires:  boost-devel
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-std-msgs

%description
ROS package for LDS(HLS-LFCD2). The LDS (Laser Distance Sensor) is a sensor
sending the data to Host for the simultaneous localization and mapping (SLAM).
Simultaneously the detecting obstacle data can also be sent to Host. HLDS
(Hitachi-LG Data Storage) is developing the technology for the moving platform
sensor such as Robot Vacuum Cleaners, Home Robot, Robotics Lawn Mower Sensor,
etc.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Wed Jan 23 2019 Pyo <pyo@robotis.com> - 1.1.0-1
- Autogenerated by Bloom

* Wed Jan 23 2019 Pyo <pyo@robotis.com> - 1.1.0-0
- Autogenerated by Bloom

* Fri Jul 20 2018 Pyo <pyo@robotis.com> - 1.0.0-0
- Autogenerated by Bloom

